"""Phase 5.2: household invites

Revision ID: 5d233a52b7e7
Revises: 6a0a7c5c8f6b
Create Date: 2025-10-28 20:31:40.234037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d233a52b7e7'
down_revision: Union[str, Sequence[str], None] = '6a0a7c5c8f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household_invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('invited_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_household_invites_household_id'), 'household_invites', ['household_id'], unique=False)
    op.create_index(op.f('ix_household_invites_invited_email'), 'household_invites', ['invited_email'], unique=False)
    op.create_index(op.f('ix_household_invites_token'), 'household_invites', ['token'], unique=True)
    op.create_foreign_key(None, 'grocery_items', 'users', ['assigned_to_user'], ['id'])
    op.create_foreign_key(None, 'grocery_items', 'households', ['household_id'], ['id'])
    op.add_column('meal_plans', sa.Column('household_id', sa.Uuid(), nullable=False))
    op.add_column('meal_plans', sa.Column('notes_per_user', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_meal_plans_household_id'), 'meal_plans', ['household_id'], unique=False)
    op.create_foreign_key(None, 'meal_plans', 'households', ['household_id'], ['id'])
    op.add_column('pantry_items', sa.Column('household_id', sa.Uuid(), nullable=False))
    op.add_column('pantry_items', sa.Column('added_by_user_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_pantry_items_household_id'), 'pantry_items', ['household_id'], unique=False)
    op.create_foreign_key(None, 'pantry_items', 'users', ['added_by_user_id'], ['id'])
    op.create_foreign_key(None, 'pantry_items', 'households', ['household_id'], ['id'])
    op.add_column('users', sa.Column('subscription_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('users', sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'subscription_status')
    op.drop_constraint(None, 'pantry_items', type_='foreignkey')
    op.drop_constraint(None, 'pantry_items', type_='foreignkey')
    op.drop_index(op.f('ix_pantry_items_household_id'), table_name='pantry_items')
    op.drop_column('pantry_items', 'added_by_user_id')
    op.drop_column('pantry_items', 'household_id')
    op.drop_constraint(None, 'meal_plans', type_='foreignkey')
    op.drop_index(op.f('ix_meal_plans_household_id'), table_name='meal_plans')
    op.drop_column('meal_plans', 'notes_per_user')
    op.drop_column('meal_plans', 'household_id')
    op.drop_constraint(None, 'grocery_items', type_='foreignkey')
    op.drop_constraint(None, 'grocery_items', type_='foreignkey')
    op.drop_index(op.f('ix_household_invites_token'), table_name='household_invites')
    op.drop_index(op.f('ix_household_invites_invited_email'), table_name='household_invites')
    op.drop_index(op.f('ix_household_invites_household_id'), table_name='household_invites')
    op.drop_table('household_invites')
    # ### end Alembic commands ###
