"""add_cook_session_servings

Revision ID: 03766c67be64
Revises: e6c7b5611bd1
Create Date: 2026-01-24 22:54:04.837739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03766c67be64'
down_revision: Union[str, None] = 'e6c7b5611bd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cook_sessions', sa.Column('servings_base', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('cook_sessions', sa.Column('servings_target', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cook_sessions', 'servings_target')
    op.drop_column('cook_sessions', 'servings_base')
    # ### end Alembic commands ###
