"""Add cascade delete to CookSession

Revision ID: 05c0902200be
Revises: 2697e4fa832b
Create Date: 2026-02-09 14:32:52.916328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c0902200be'
down_revision: Union[str, None] = '2697e4fa832b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cook_sessions_recipe_id_fkey', 'cook_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'cook_sessions', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cook_sessions', type_='foreignkey')
    op.create_foreign_key('cook_sessions_recipe_id_fkey', 'cook_sessions', 'recipes', ['recipe_id'], ['id'])
    # ### end Alembic commands ###
