"""add_recipe_source_hash

Revision ID: 0ad2e4e664e1
Revises: 2c331c2c5e6c
Create Date: 2026-02-07 01:56:44.515356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad2e4e664e1'
down_revision: Union[str, None] = '2c331c2c5e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingredient_density_overrides_ingredient_key', table_name='ingredient_density_overrides')
    op.drop_index('ix_ingredient_density_overrides_workspace_id', table_name='ingredient_density_overrides')
    op.add_column('recipes', sa.Column('source_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_recipes_source_hash'), 'recipes', ['source_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipes_source_hash'), table_name='recipes')
    op.drop_column('recipes', 'source_hash')
    op.create_index('ix_ingredient_density_overrides_workspace_id', 'ingredient_density_overrides', ['workspace_id'], unique=False)
    op.create_index('ix_ingredient_density_overrides_ingredient_key', 'ingredient_density_overrides', ['ingredient_key'], unique=False)
    # ### end Alembic commands ###
