"""add_macro_and_tip_entries

Revision ID: 0dcdd7be93e1
Revises: 0ad2e4e664e1
Create Date: 2026-02-07 03:09:52.516531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dcdd7be93e1'
down_revision: Union[str, None] = '0ad2e4e664e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_macro_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('calories_min', sa.Integer(), nullable=True),
    sa.Column('calories_max', sa.Integer(), nullable=True),
    sa.Column('protein_min', sa.Integer(), nullable=True),
    sa.Column('protein_max', sa.Integer(), nullable=True),
    sa.Column('carbs_min', sa.Integer(), nullable=True),
    sa.Column('carbs_max', sa.Integer(), nullable=True),
    sa.Column('fat_min', sa.Integer(), nullable=True),
    sa.Column('fat_max', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('context_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recipe_macro_workspace_recipe', 'recipe_macro_entries', ['workspace_id', 'recipe_id'], unique=False)
    op.create_table('recipe_tip_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('tips_json', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('food_safety_json', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('context_hash', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recipe_tips_workspace_recipe_scope', 'recipe_tip_entries', ['workspace_id', 'recipe_id', 'scope'], unique=False)
    op.drop_column('recipe_note_entries', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_note_entries', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index('ix_recipe_tips_workspace_recipe_scope', table_name='recipe_tip_entries')
    op.drop_table('recipe_tip_entries')
    op.drop_index('ix_recipe_macro_workspace_recipe', table_name='recipe_macro_entries')
    op.drop_table('recipe_macro_entries')
    # ### end Alembic commands ###
