"""Add method switching columns to cook_sessions

Revision ID: 1ce98d8ef389
Revises: 03766c67be64
Create Date: 2026-01-25 04:22:19.868412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ce98d8ef389'
down_revision: Union[str, None] = '03766c67be64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cook_sessions', sa.Column('method_key', sa.String(length=50), nullable=True))
    op.add_column('cook_sessions', sa.Column('steps_override', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('cook_sessions', sa.Column('method_tradeoffs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('cook_sessions', sa.Column('method_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cook_sessions', 'method_generated_at')
    op.drop_column('cook_sessions', 'method_tradeoffs')
    op.drop_column('cook_sessions', 'steps_override')
    op.drop_column('cook_sessions', 'method_key')
    # ### end Alembic commands ###
