"""create_meal_logs_table

Revision ID: 1e7cd8d1d2a4
Revises: 683226252910
Create Date: 2026-02-16 18:19:10.595427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e7cd8d1d2a4'
down_revision: Union[str, None] = '683226252910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('servings', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('macros_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meal_logs_timestamp', 'meal_logs', ['timestamp'], unique=False)
    op.create_index('ix_meal_logs_workspace_id', 'meal_logs', ['workspace_id'], unique=False)
    op.add_column('recipes', sa.Column('macros', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'macros')
    op.drop_index('ix_meal_logs_workspace_id', table_name='meal_logs')
    op.drop_index('ix_meal_logs_timestamp', table_name='meal_logs')
    op.drop_table('meal_logs')
    # ### end Alembic commands ###
