"""Add total_minutes and total_minutes_source

Revision ID: 2697e4fa832b
Revises: f46104676bae
Create Date: 2026-02-09 14:25:30.093111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2697e4fa832b'
down_revision: Union[str, None] = 'f46104676bae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('total_minutes', sa.Integer(), nullable=True))
    op.add_column('recipes', sa.Column('total_minutes_source', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'total_minutes_source')
    op.drop_column('recipes', 'total_minutes')
    # ### end Alembic commands ###
