"""add_recipe_variants_and_active_ptr

Revision ID: 40e1b4f7a27d
Revises: d8be09e837fa
Create Date: 2026-02-06 23:30:45.135352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40e1b4f7a27d'
down_revision: Union[str, None] = 'd8be09e837fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



import uuid

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_variants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=50), server_default='ai', nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recipe_variants_recipe_id', 'recipe_variants', ['recipe_id'], unique=False)
    op.create_index('ix_recipe_variants_workspace_id', 'recipe_variants', ['workspace_id'], unique=False)
    op.add_column('recipes', sa.Column('active_variant_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'recipes', 'recipe_variants', ['active_variant_id'], ['id'], ondelete='SET NULL', use_alter=True)
    
    # --- Data Migration: Create Initial "Original" Variants ---
    conn = op.get_bind()
    meta = sa.MetaData()
    
    # Define needed table proxies
    recipes_t = sa.Table(
        'recipes', meta,
        sa.Column('id', sa.String(36), primary_key=True),
        sa.Column('workspace_id', sa.String(36)),
        sa.Column('title', sa.String(200)),
        sa.Column('servings', sa.Integer),
        sa.Column('time_minutes', sa.Integer),
        sa.Column('tags', postgresql.ARRAY(sa.String)),
        sa.Column('active_variant_id', sa.String(36))
    )
    
    steps_t = sa.Table(
        'recipe_steps', meta,
        sa.Column('recipe_id', sa.String(36)),
        sa.Column('step_index', sa.Integer),
        sa.Column('title', sa.String(200)),
        sa.Column('bullets', postgresql.ARRAY(sa.Text)),
        sa.Column('minutes_est', sa.Integer)
    )
    
    ingredients_t = sa.Table(
        'recipe_ingredients', meta,
        sa.Column('recipe_id', sa.String(36)),
        sa.Column('name', sa.String(200)),
        sa.Column('qty', sa.Numeric),
        sa.Column('unit', sa.String(20)),
        sa.Column('category', sa.String(50))
    )
    
    variants_t = sa.Table(
        'recipe_variants', meta,
        sa.Column('id', sa.String(36)),
        sa.Column('workspace_id', sa.String(36)),
        sa.Column('recipe_id', sa.String(36)),
        sa.Column('label', sa.String(100)),
        sa.Column('content_json', postgresql.JSONB),
        sa.Column('created_by', sa.String(50)),
    )

    # Fetch all recipes
    recipe_rows = conn.execute(sa.select(recipes_t)).fetchall()
    
    for r in recipe_rows:
        r_id = r.id
        
        # Steps
        step_rows = conn.execute(
            sa.select(steps_t).where(steps_t.c.recipe_id == r_id).order_by(steps_t.c.step_index)
        ).fetchall()
        
        # Ingredients
        ing_rows = conn.execute(
            sa.select(ingredients_t).where(ingredients_t.c.recipe_id == r_id)
        ).fetchall()
        
        # Build JSON
        steps_list = []
        for s in step_rows:
            txt = ""
            # formatting logic: if title is meaningful, bold it
            if s.title and not s.title.lower().startswith('step '):
                txt += f"**{s.title}:** "
            
            # append bullets
            if s.bullets:
                txt += " ".join(s.bullets)
            elif not txt:
                # fallback if no bullets and title was skipped or empty
                 if s.title: txt = s.title
                 
            steps_list.append(txt)
            
        ing_list = []
        for i in ing_rows:
            ing_list.append({
                "item": i.name,
                "quantity": float(i.qty) if i.qty is not None else None,
                "unit": i.unit,
                "section": i.category if i.category else "Main"
            })
            
        content = {
            "title": r.title,
            "yield": {"servings": r.servings if r.servings else 4, "unit": "servings"},
            "tags": r.tags if r.tags else [],
            "total_time_minutes": r.time_minutes,
            "ingredients": ing_list,
            "steps": steps_list,
            # We omit tips/macros/storage here for simplicity, 
            # as they are separate tables and will be re-fetched by the UI if needed,
            # or the user can "Refine" to pull them in via AI later. 
            "notes": "Migrated from original recipe."
        }
        
        # Insert Variant
        new_variant_id = str(uuid.uuid4())
        conn.execute(variants_t.insert().values(
            id=new_variant_id,
            workspace_id=r.workspace_id,
            recipe_id=r_id,
            label="Original",
            content_json=content,
            created_by="system-migration"
        ))
        
        # Update Recipe Active Pointer
        conn.execute(
            recipes_t.update().where(recipes_t.c.id == r_id).values(active_variant_id=new_variant_id)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'active_variant_id')
    op.drop_index('ix_recipe_variants_workspace_id', table_name='recipe_variants')
    op.drop_index('ix_recipe_variants_recipe_id', table_name='recipe_variants')
    op.drop_table('recipe_variants')
    # ### end Alembic commands ###
