"""create grocery tables

Revision ID: 4f77e906b671
Revises: d9b821fb40c7
Create Date: 2026-01-23 23:59:58.300876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f77e906b671'
down_revision: Union[str, None] = 'd9b821fb40c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grocery_lists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grocery_lists_workspace_id', 'grocery_lists', ['workspace_id'], unique=False)
    op.create_table('grocery_list_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grocery_list_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grocery_list_id'], ['grocery_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grocery_list_items_list_id', 'grocery_list_items', ['grocery_list_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recipe_ingredients_recipe_id', 'recipe_ingredients', ['recipe_id'], unique=False)
    # op.drop_index('ix_recipe_images_pending_poll', table_name='recipe_images')
    # op.drop_index('ix_recipes_workspace_created_desc', table_name='recipes')
    # op.drop_index('ix_workspaces_slug_unique', table_name='workspaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_workspaces_slug_unique', 'workspaces', ['slug'], unique=True)
    op.create_index('ix_recipes_workspace_created_desc', 'recipes', ['workspace_id', 'created_at'], unique=False)
    op.create_index('ix_recipe_images_pending_poll', 'recipe_images', ['status', 'next_attempt_at'], unique=False)
    op.drop_index('ix_recipe_ingredients_recipe_id', table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index('ix_grocery_list_items_list_id', table_name='grocery_list_items')
    op.drop_table('grocery_list_items')
    op.drop_index('ix_grocery_lists_workspace_id', table_name='grocery_lists')
    op.drop_table('grocery_lists')
    # ### end Alembic commands ###
