"""Add data_json to RecipeNoteEntry

Revision ID: 6518be12fb93
Revises: c19af3872dfc
Create Date: 2026-02-06 16:42:16.156955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6518be12fb93'
down_revision: Union[str, None] = 'c19af3872dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cook_sessions', sa.Column('recap_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('recipe_note_entries', sa.Column('data_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_note_entries', 'data_json')
    op.drop_column('cook_sessions', 'recap_json')
    # ### end Alembic commands ###
