"""add_ingredient_density_overrides

Revision ID: 83ea189c810c
Revises: 589e77145b29
Create Date: 2026-02-06 19:57:36.792210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ea189c810c'
down_revision: Union[str, None] = '589e77145b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_density_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('ingredient_key', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('density_g_per_ml', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('source', sa.String(length=50), server_default='user', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'ingredient_key', name='uq_workspace_ingredient_key')
    )
    op.create_index('ix_ingredient_density_key', 'ingredient_density_overrides', ['ingredient_key'], unique=False)
    op.create_index('ix_ingredient_density_workspace_id', 'ingredient_density_overrides', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ingredient_density_workspace_id', table_name='ingredient_density_overrides')
    op.drop_index('ix_ingredient_density_key', table_name='ingredient_density_overrides')
    op.drop_table('ingredient_density_overrides')
    # ### end Alembic commands ###
