"""Add cook session summary fields

Revision ID: b3cf48d03393
Revises: f7a8b9c0d1e2
Create Date: 2026-01-25 22:50:45.872902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3cf48d03393'
down_revision: Union[str, None] = 'f7a8b9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cook_sessions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cook_sessions', sa.Column('abandoned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cook_sessions', sa.Column('ended_reason', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cook_sessions', 'ended_reason')
    op.drop_column('cook_sessions', 'abandoned_at')
    op.drop_column('cook_sessions', 'completed_at')
    # ### end Alembic commands ###
