"""Add hands_free to cook_sessions

Revision ID: c19af3872dfc
Revises: 487e75fd144b
Create Date: 2026-02-06 00:20:42.085643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c19af3872dfc'
down_revision: Union[str, None] = '487e75fd144b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cook_sessions', sa.Column('hands_free', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('cook_sessions', sa.Column('state_version', sa.Integer(), server_default='1', nullable=False))
    op.drop_index('ix_grocery_list_items_pantry_item_id', table_name='grocery_list_items')
    op.alter_column('note_insights_cache', 'scope',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('pantry_items', 'expires_at')
    op.drop_index('ix_recipe_note_entries_tags', table_name='recipe_note_entries', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_recipe_note_entries_tags', 'recipe_note_entries', ['tags'], unique=False, postgresql_using='gin')
    op.add_column('pantry_items', sa.Column('expires_at', sa.DATE(), autoincrement=False, nullable=True))
    op.alter_column('note_insights_cache', 'scope',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index('ix_grocery_list_items_pantry_item_id', 'grocery_list_items', ['pantry_item_id'], unique=False)
    op.drop_column('cook_sessions', 'state_version')
    op.drop_column('cook_sessions', 'hands_free')
    # ### end Alembic commands ###
