"""Update indexes for insights

Revision ID: d8be09e837fa
Revises: 0dcdd7be93e1
Create Date: 2026-02-06 22:34:44.587216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8be09e837fa'
down_revision: Union[str, None] = '0dcdd7be93e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipe_macro_workspace_recipe', table_name='recipe_macro_entries')
    op.create_index('ix_recipe_macro_ws_recipe_created', 'recipe_macro_entries', ['workspace_id', 'recipe_id', 'created_at'], unique=False)
    op.create_index('ix_recipe_note_entries_unique_session', 'recipe_note_entries', ['session_id', 'recipe_id'], unique=True)
    op.drop_index('ix_recipe_tips_workspace_recipe_scope', table_name='recipe_tip_entries')
    op.create_index('ix_recipe_tips_ws_recipe_scope_created', 'recipe_tip_entries', ['workspace_id', 'recipe_id', 'scope', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipe_tips_ws_recipe_scope_created', table_name='recipe_tip_entries')
    op.create_index('ix_recipe_tips_workspace_recipe_scope', 'recipe_tip_entries', ['workspace_id', 'recipe_id', 'scope'], unique=False)
    op.drop_index('ix_recipe_note_entries_unique_session', table_name='recipe_note_entries')
    op.drop_index('ix_recipe_macro_ws_recipe_created', table_name='recipe_macro_entries')
    op.create_index('ix_recipe_macro_workspace_recipe', 'recipe_macro_entries', ['workspace_id', 'recipe_id'], unique=False)
    # ### end Alembic commands ###
