"""create pantry_items

Revision ID: d9b821fb40c7
Revises: 003_worker_locking
Create Date: 2026-01-23 22:56:23.338586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9b821fb40c7'
down_revision: Union[str, None] = '003_worker_locking'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pantry_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('qty', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pantry_items_workspace_id_expires_on', 'pantry_items', ['workspace_id', 'expires_on'], unique=False)
    op.create_index('ix_pantry_items_workspace_id_lower_name', 'pantry_items', ['workspace_id', sa.text("lower('name')")], unique=False)
    op.alter_column('recipe_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # op.drop_index('ix_recipe_images_pending_poll', table_name='recipe_images')
    op.alter_column('recipes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # op.drop_index('ix_recipes_workspace_created_desc', table_name='recipes')
    op.alter_column('workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # op.drop_index('ix_workspaces_slug_unique', table_name='workspaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_workspaces_slug_unique', 'workspaces', ['slug'], unique=True)
    op.alter_column('workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_recipes_workspace_created_desc', 'recipes', ['workspace_id', 'created_at'], unique=False)
    op.alter_column('recipes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_recipe_images_pending_poll', 'recipe_images', ['status', 'next_attempt_at'], unique=False)
    op.alter_column('recipe_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_pantry_items_workspace_id_lower_name', table_name='pantry_items')
    op.drop_index('ix_pantry_items_workspace_id_expires_on', table_name='pantry_items')
    op.drop_table('pantry_items')
    # ### end Alembic commands ###
