"""Add auto_step fields to cook_sessions

Revision ID: e426570bcb89
Revises: a1b2c3d4e5f6
Create Date: 2026-01-25 18:51:00.448897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e426570bcb89'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cook_sessions', sa.Column('auto_step_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('cook_sessions', sa.Column('auto_step_mode', sa.String(length=20), server_default='suggest', nullable=False))
    op.add_column('cook_sessions', sa.Column('auto_step_suggested_index', sa.Integer(), nullable=True))
    op.add_column('cook_sessions', sa.Column('auto_step_confidence', sa.Float(), nullable=True))
    op.add_column('cook_sessions', sa.Column('auto_step_reason', sa.String(length=100), nullable=True))
    op.add_column('cook_sessions', sa.Column('manual_override_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cook_sessions', sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cook_sessions', sa.Column('last_interaction_step_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cook_sessions', 'last_interaction_step_index')
    op.drop_column('cook_sessions', 'last_interaction_at')
    op.drop_column('cook_sessions', 'manual_override_until')
    op.drop_column('cook_sessions', 'auto_step_reason')
    op.drop_column('cook_sessions', 'auto_step_confidence')
    op.drop_column('cook_sessions', 'auto_step_suggested_index')
    op.drop_column('cook_sessions', 'auto_step_mode')
    op.drop_column('cook_sessions', 'auto_step_enabled')
    # ### end Alembic commands ###
