"""Add ended_at to cook_sessions

Revision ID: e6c7b5611bd1
Revises: 82205a222a97
Create Date: 2026-01-25 02:19:24.403334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c7b5611bd1'
down_revision: Union[str, None] = '82205a222a97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cook_sessions', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_cook_sessions_workspace_recipe_status', table_name='cook_sessions')
    op.drop_index('ix_cook_sessions_workspace_status_started', table_name='cook_sessions')
    op.drop_constraint('uq_meal_plan_entry_slot', 'meal_plan_entries', type_='unique')
    op.drop_constraint('uq_meal_plan_workspace_week', 'meal_plans', type_='unique')
    op.drop_index('ix_recipe_images_pending_poll', table_name='recipe_images')
    op.drop_index('ix_recipes_workspace_created_desc', table_name='recipes')
    op.drop_constraint('uq_user_prefs_workspace', 'user_prefs', type_='unique')
    op.create_index('ix_user_prefs_workspace', 'user_prefs', ['workspace_id'], unique=False)
    op.drop_index('ix_workspaces_slug_unique', table_name='workspaces')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_workspaces_slug_unique', 'workspaces', ['slug'], unique=True)
    op.drop_index('ix_user_prefs_workspace', table_name='user_prefs')
    op.create_unique_constraint('uq_user_prefs_workspace', 'user_prefs', ['workspace_id'])
    op.create_index('ix_recipes_workspace_created_desc', 'recipes', ['workspace_id', 'created_at'], unique=False)
    op.create_index('ix_recipe_images_pending_poll', 'recipe_images', ['status', 'next_attempt_at'], unique=False)
    op.create_unique_constraint('uq_meal_plan_workspace_week', 'meal_plans', ['workspace_id', 'week_start'])
    op.create_unique_constraint('uq_meal_plan_entry_slot', 'meal_plan_entries', ['meal_plan_id', 'date', 'meal_type'])
    op.create_index('ix_cook_sessions_workspace_status_started', 'cook_sessions', ['workspace_id', 'status', sa.text('started_at DESC')], unique=False)
    op.create_index('ix_cook_sessions_workspace_recipe_status', 'cook_sessions', ['workspace_id', 'recipe_id', 'status'], unique=False)
    op.drop_column('cook_sessions', 'ended_at')
    # ### end Alembic commands ###
