"""Add deleted_at to RecipeNoteEntry

Revision ID: f46104676bae
Revises: 40e1b4f7a27d
Create Date: 2026-02-07 06:06:35.903475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f46104676bae'
down_revision: Union[str, None] = '40e1b4f7a27d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_note_entries', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_note_entries', 'deleted_at')
    # ### end Alembic commands ###
